#!/usr/bin/env bash
# Install the checkout the scheduled jobs run out of.
#
# hermes cron resolves a job's `script` against HERMES_HOME/scripts and refuses
# a path resolving outside it (hermes_cli/cron.py, _script_health_issue), so no
# job can name `tools-live-run` directly. The shims are how one reaches it.
#
# A shim inside the live checkout would be rewritten by the refresh it just
# asked for, so they are real files in a real directory.
#
# Idempotent. `--check` reports and changes nothing.
set -euo pipefail
# An unmatched glob otherwise survives as its own literal, and the loops below
# would install a shim named `*.sh` and a symlink named `*`.
shopt -s nullglob

LIVE=${LIVE_REPO:-$HOME/hermes-tools-live}
WORK=${WORK_REPO:-$HOME/hermes-tools}
BIN_DIR=${LIVE_BIN_DIR:-$HOME/bin}
COPY_DIR=${LIVE_COPY_DIR:-$HOME/.local/bin}
SCRIPTS_DIR=${HERMES_SCRIPTS_DIR:-$HOME/.hermes/scripts}

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

say() { printf '%s\n' "$*"; }
run() { if [ "$CHECK" = 1 ]; then say "  would: $*"; else "$@"; fi; }

ORIGIN=$(git -C "$WORK" remote get-url origin)

say "==> live checkout: $LIVE"
if [ ! -d "$LIVE/.git" ]; then
	say "  clone $ORIGIN"
	# A clone, not a worktree: a worktree shares the working checkout's object
	# store, so deleting that checkout takes the jobs down with it.
	run git clone --quiet --branch main "$ORIGIN" "$LIVE"
else
	run git -C "$LIVE" fetch --quiet origin
	run git -C "$LIVE" checkout --quiet main
	run git -C "$LIVE" reset --hard --quiet origin/main
fi

say "==> wrapper copy: $COPY_DIR/tools-live-run"
run mkdir -p "$COPY_DIR"
# cp, never ln: the wrapper resets the live checkout, so it must not live in it.
run cp "$LIVE/bin/tools-live-run" "$COPY_DIR/tools-live-run"
run chmod 755 "$COPY_DIR/tools-live-run"

say "==> job shims: $SCRIPTS_DIR"
if [ -L "$SCRIPTS_DIR" ]; then
	say "  replacing symlink -> $(readlink "$SCRIPTS_DIR")"
	run rm -f "$SCRIPTS_DIR"
fi
run mkdir -p "$SCRIPTS_DIR"
shims=("$LIVE"/pipeline/*.sh)
[ ${#shims[@]} -gt 0 ] || { echo "no pipeline scripts in $LIVE/pipeline; nothing for cron to reach" >&2; exit 3; }
for src in "${shims[@]}"; do
	name=$(basename "$src")
	say "  shim $name"
	if [ "$CHECK" = 1 ]; then continue; fi
	# Named, not left to the wrapper's default: a cron job runs with whatever
	# HOME the scheduler hands it.
	cat >"$SCRIPTS_DIR/$name" <<SHIM
#!/usr/bin/env bash
# Generated by install/live-checkout/setup.sh. Edits belong in the repository.
export LIVE_REPO="$LIVE"
exec "$COPY_DIR/tools-live-run" "$name" "\$@"
SHIM
	chmod 755 "$SCRIPTS_DIR/$name"
done

say "==> tool symlinks: $BIN_DIR -> $LIVE/bin"
run mkdir -p "$BIN_DIR"
for tool in "$LIVE"/bin/*; do
	name=$(basename "$tool")
	# Installed as a copy above.
	[ "$name" = "tools-live-run" ] && continue
	current=$(readlink -f "$BIN_DIR/$name" 2>/dev/null || true)
	[ "$current" = "$(readlink -f "$tool")" ] && continue
	say "  link $name"
	run ln -sfn "$tool" "$BIN_DIR/$name"
done

say
if [ "$CHECK" = 1 ]; then
	say "check only; nothing changed."
else
	say "installed. Verify with: hermes-doctor live"
fi
